# These are supported funding model platforms

github: ameliakiara
patreon: https://www.patreon.com/ameliakiara
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie:
custom: https://trakteer.id/ameliakiara
